image: archlinux
packages:
  - libxslt
  - python2
  - rsync
secrets:
  - 3612b5e9-3819-4f44-ad00-bd5bf63e8dad # deploy key
sources:
  - https://github.com/clonkspot/crdocs

tasks:
  - build: |
      cd crdocs
      make -j $(nproc)

      [[ "$GITHUB_REF" = refs/heads/master ]] || complete-build
  - deploy: |
      cd crdocs
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -rv --delete online/{de,en} clnk@lupus.uberspace.de:~/www/crdocs.clonkspot.org/
