image: archlinux
packages:
  - libxslt
  - python2
  - python2-libxml2
  - rsync
secrets:
  - 2512d659-6458-48cc-9a91-4d9793baa7a3 # deploy key
sources:
  - https://github.com/clonkspot/crdocs

tasks:
  - build: |
      cd crdocs
      make -j $(nproc)

      [[ "$GITHUB_REF" = refs/heads/master ]] || complete-build
  - deploy: |
      cd crdocs
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -rv --delete online/{de,en} crdocs@openclonk.org:~/www/
