name: Build Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends xsltproc python-libxml2 gettext -y
    
    - name: Build
      run: make
    
    - uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: pages

    - name: Deploy
      run: |
        rm -rf pages/docs
        mv online pages/docs
        cd pages
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs
        git commit -m "$GITHUB_SHA"
        git push
